//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class OwnCoverage {
    
    private string coveredStatementsField;
    
    private string totalStatementsField;
    
    private string coveragePercentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveredStatements {
        get {
            return this.coveredStatementsField;
        }
        set {
            this.coveredStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TotalStatements {
        get {
            return this.totalStatementsField;
        }
        set {
            this.totalStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveragePercent {
        get {
            return this.coveragePercentField;
        }
        set {
            this.coveragePercentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class AnonymousMethod {

    private List<OwnCoverage> ownCoverageField;

    private List<AnonymousMethod> anonymousMethod1Field;
    
    private string nameField;
    
    private string coveredStatementsField;
    
    private string totalStatementsField;
    
    private string coveragePercentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OwnCoverage")]
    public List<OwnCoverage> OwnCoverage {
        get {
            return this.ownCoverageField;
        }
        set {
            this.ownCoverageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AnonymousMethod")]
    public List<AnonymousMethod> AnonymousMethod1 {
        get {
            return this.anonymousMethod1Field;
        }
        set {
            this.anonymousMethod1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveredStatements {
        get {
            return this.coveredStatementsField;
        }
        set {
            this.coveredStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TotalStatements {
        get {
            return this.totalStatementsField;
        }
        set {
            this.totalStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveragePercent {
        get {
            return this.coveragePercentField;
        }
        set {
            this.coveragePercentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Root {

    private List<RootProject> projectField;
    
    private string coveredStatementsField;
    
    private string totalStatementsField;
    
    private string coveragePercentField;
    
    private string reportTypeField;
    
    private string dotCoverVersionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Project", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public List<RootProject> Project {
        get {
            return this.projectField;
        }
        set {
            this.projectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveredStatements {
        get {
            return this.coveredStatementsField;
        }
        set {
            this.coveredStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TotalStatements {
        get {
            return this.totalStatementsField;
        }
        set {
            this.totalStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveragePercent {
        get {
            return this.coveragePercentField;
        }
        set {
            this.coveragePercentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ReportType {
        get {
            return this.reportTypeField;
        }
        set {
            this.reportTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DotCoverVersion {
        get {
            return this.dotCoverVersionField;
        }
        set {
            this.dotCoverVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RootProject {

    private List<RootProjectNamespace> namespaceField;
    
    private string nameField;
    
    private string coveredStatementsField;
    
    private string totalStatementsField;
    
    private string coveragePercentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Namespace", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public List<RootProjectNamespace> Namespace {
        get {
            return this.namespaceField;
        }
        set {
            this.namespaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveredStatements {
        get {
            return this.coveredStatementsField;
        }
        set {
            this.coveredStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TotalStatements {
        get {
            return this.totalStatementsField;
        }
        set {
            this.totalStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveragePercent {
        get {
            return this.coveragePercentField;
        }
        set {
            this.coveragePercentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RootProjectNamespace {

    private List<RootProjectNamespaceType> typeField;
    
    private string nameField;
    
    private string coveredStatementsField;
    
    private string totalStatementsField;
    
    private string coveragePercentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public List<RootProjectNamespaceType> Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveredStatements {
        get {
            return this.coveredStatementsField;
        }
        set {
            this.coveredStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TotalStatements {
        get {
            return this.totalStatementsField;
        }
        set {
            this.totalStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveragePercent {
        get {
            return this.coveragePercentField;
        }
        set {
            this.coveragePercentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RootProjectNamespaceType {

    private List<RootProjectNamespaceTypeConstructor> constructorField;

    private List<RootProjectNamespaceTypeProperty> propertyField;

    private List<RootProjectNamespaceTypeEvent> eventField;

    private List<RootProjectNamespaceTypeMethod> methodField;
    
    private string nameField;
    
    private string coveredStatementsField;
    
    private string totalStatementsField;
    
    private string coveragePercentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Constructor", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public List<RootProjectNamespaceTypeConstructor> Constructor {
        get {
            return this.constructorField;
        }
        set {
            this.constructorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Property", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public List<RootProjectNamespaceTypeProperty> Property {
        get {
            return this.propertyField;
        }
        set {
            this.propertyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Event", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public List<RootProjectNamespaceTypeEvent> Event {
        get {
            return this.eventField;
        }
        set {
            this.eventField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Method", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public List<RootProjectNamespaceTypeMethod> Method {
        get {
            return this.methodField;
        }
        set {
            this.methodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveredStatements {
        get {
            return this.coveredStatementsField;
        }
        set {
            this.coveredStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TotalStatements {
        get {
            return this.totalStatementsField;
        }
        set {
            this.totalStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveragePercent {
        get {
            return this.coveragePercentField;
        }
        set {
            this.coveragePercentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RootProjectNamespaceTypeConstructor {

    private List<OwnCoverage> ownCoverageField;

    private List<AnonymousMethod> anonymousMethodField;
    
    private string nameField;
    
    private string coveredStatementsField;
    
    private string totalStatementsField;
    
    private string coveragePercentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OwnCoverage")]
    public List<OwnCoverage> OwnCoverage {
        get {
            return this.ownCoverageField;
        }
        set {
            this.ownCoverageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AnonymousMethod")]
    public List<AnonymousMethod> AnonymousMethod {
        get {
            return this.anonymousMethodField;
        }
        set {
            this.anonymousMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveredStatements {
        get {
            return this.coveredStatementsField;
        }
        set {
            this.coveredStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TotalStatements {
        get {
            return this.totalStatementsField;
        }
        set {
            this.totalStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveragePercent {
        get {
            return this.coveragePercentField;
        }
        set {
            this.coveragePercentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RootProjectNamespaceTypeProperty {

    private List<RootProjectNamespaceTypePropertyPropertyGetter> propertyGetterField;

    private List<RootProjectNamespaceTypePropertyPropertySetter> propertySetterField;
    
    private string nameField;
    
    private string coveredStatementsField;
    
    private string totalStatementsField;
    
    private string coveragePercentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PropertyGetter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public List<RootProjectNamespaceTypePropertyPropertyGetter> PropertyGetter {
        get {
            return this.propertyGetterField;
        }
        set {
            this.propertyGetterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PropertySetter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public List<RootProjectNamespaceTypePropertyPropertySetter> PropertySetter {
        get {
            return this.propertySetterField;
        }
        set {
            this.propertySetterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveredStatements {
        get {
            return this.coveredStatementsField;
        }
        set {
            this.coveredStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TotalStatements {
        get {
            return this.totalStatementsField;
        }
        set {
            this.totalStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveragePercent {
        get {
            return this.coveragePercentField;
        }
        set {
            this.coveragePercentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RootProjectNamespaceTypePropertyPropertyGetter {
    
    private string coveredStatementsField;
    
    private string totalStatementsField;
    
    private string coveragePercentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveredStatements {
        get {
            return this.coveredStatementsField;
        }
        set {
            this.coveredStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TotalStatements {
        get {
            return this.totalStatementsField;
        }
        set {
            this.totalStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveragePercent {
        get {
            return this.coveragePercentField;
        }
        set {
            this.coveragePercentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RootProjectNamespaceTypePropertyPropertySetter {
    
    private string coveredStatementsField;
    
    private string totalStatementsField;
    
    private string coveragePercentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveredStatements {
        get {
            return this.coveredStatementsField;
        }
        set {
            this.coveredStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TotalStatements {
        get {
            return this.totalStatementsField;
        }
        set {
            this.totalStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveragePercent {
        get {
            return this.coveragePercentField;
        }
        set {
            this.coveragePercentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RootProjectNamespaceTypeEvent {

    private List<RootProjectNamespaceTypeEventEventAdder> eventAdderField;

    private List<RootProjectNamespaceTypeEventEventRemover> eventRemoverField;
    
    private string nameField;
    
    private string coveredStatementsField;
    
    private string totalStatementsField;
    
    private string coveragePercentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("EventAdder", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public List<RootProjectNamespaceTypeEventEventAdder> EventAdder {
        get {
            return this.eventAdderField;
        }
        set {
            this.eventAdderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("EventRemover", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public List<RootProjectNamespaceTypeEventEventRemover> EventRemover {
        get {
            return this.eventRemoverField;
        }
        set {
            this.eventRemoverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveredStatements {
        get {
            return this.coveredStatementsField;
        }
        set {
            this.coveredStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TotalStatements {
        get {
            return this.totalStatementsField;
        }
        set {
            this.totalStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveragePercent {
        get {
            return this.coveragePercentField;
        }
        set {
            this.coveragePercentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RootProjectNamespaceTypeEventEventAdder {
    
    private string coveredStatementsField;
    
    private string totalStatementsField;
    
    private string coveragePercentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveredStatements {
        get {
            return this.coveredStatementsField;
        }
        set {
            this.coveredStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TotalStatements {
        get {
            return this.totalStatementsField;
        }
        set {
            this.totalStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveragePercent {
        get {
            return this.coveragePercentField;
        }
        set {
            this.coveragePercentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RootProjectNamespaceTypeEventEventRemover {
    
    private string coveredStatementsField;
    
    private string totalStatementsField;
    
    private string coveragePercentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveredStatements {
        get {
            return this.coveredStatementsField;
        }
        set {
            this.coveredStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TotalStatements {
        get {
            return this.totalStatementsField;
        }
        set {
            this.totalStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveragePercent {
        get {
            return this.coveragePercentField;
        }
        set {
            this.coveragePercentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RootProjectNamespaceTypeMethod {

    private List<RootProjectNamespaceTypeMethodInternalCompiledMethod> internalCompiledMethodField;

    private List<OwnCoverage> ownCoverageField;

    private List<AnonymousMethod> anonymousMethodField;
    
    private string nameField;
    
    private string coveredStatementsField;
    
    private string totalStatementsField;
    
    private string coveragePercentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("InternalCompiledMethod", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public List<RootProjectNamespaceTypeMethodInternalCompiledMethod> InternalCompiledMethod {
        get {
            return this.internalCompiledMethodField;
        }
        set {
            this.internalCompiledMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OwnCoverage")]
    public List<OwnCoverage> OwnCoverage {
        get {
            return this.ownCoverageField;
        }
        set {
            this.ownCoverageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AnonymousMethod")]
    public List<AnonymousMethod> AnonymousMethod {
        get {
            return this.anonymousMethodField;
        }
        set {
            this.anonymousMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveredStatements {
        get {
            return this.coveredStatementsField;
        }
        set {
            this.coveredStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TotalStatements {
        get {
            return this.totalStatementsField;
        }
        set {
            this.totalStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveragePercent {
        get {
            return this.coveragePercentField;
        }
        set {
            this.coveragePercentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RootProjectNamespaceTypeMethodInternalCompiledMethod {

    private List<OwnCoverage> ownCoverageField;

    private List<AnonymousMethod> anonymousMethodField;
    
    private string nameField;
    
    private string coveredStatementsField;
    
    private string totalStatementsField;
    
    private string coveragePercentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OwnCoverage")]
    public List<OwnCoverage> OwnCoverage {
        get {
            return this.ownCoverageField;
        }
        set {
            this.ownCoverageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AnonymousMethod")]
    public List<AnonymousMethod> AnonymousMethod {
        get {
            return this.anonymousMethodField;
        }
        set {
            this.anonymousMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveredStatements {
        get {
            return this.coveredStatementsField;
        }
        set {
            this.coveredStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TotalStatements {
        get {
            return this.totalStatementsField;
        }
        set {
            this.totalStatementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CoveragePercent {
        get {
            return this.coveragePercentField;
        }
        set {
            this.coveragePercentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {

    private List<object> itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AnonymousMethod", typeof(AnonymousMethod))]
    [System.Xml.Serialization.XmlElementAttribute("OwnCoverage", typeof(OwnCoverage))]
    [System.Xml.Serialization.XmlElementAttribute("Root", typeof(Root))]
    public List<object> Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
